### ISSUE TITLE
Opponent Map Win % Stats in Match Room

### ISSUE THREAD

**Issue by timche** [faceit-enhancer/faceit-enhancer#10]
As suggested on Reddit: https://www.reddit.com/r/FACEITEnhancer/comments/8bst51/few_suggestions/

> Show map win/lose stats of players in Match room while voting maps. So you can see if your opponent has a very high win rate at map X and you can ban it if its very high. You can limit it to the last 10 games played on the map so its only recently games and has more weight for voting. I think putting it in a UI is a little bit tricky but if you need an idea feel free to message me and i will create a concept for you (i already have one in my mind what would work well).

This is a really crazy feature and was also [suggested very early already](https://www.reddit.com/r/GlobalOffensive/comments/82eq8j/ive_developed_faceit_enhancer_to_enhance_the/dv9xr9r/).

**Comment by Morabotti** [comment]
I started doing this. I want some clarifications before full implementation. Here is my WIP UI proposition:

![tttt](https://user-images.githubusercontent.com/42501026/94731706-e26c5080-036d-11eb-9485-4c6496d12fd5.png)

Currently I implemented this by calculating wins from past 20 games for every player. Should this be changed to use global win percentages or something else?

Currently there is alot of free horizontal space so we could also show `games played avg / win% of those games`. Should we show an additional row for explanation for example like this (rough version, needs adjusting):

![rough](https://user-images.githubusercontent.com/42501026/94732787-670b9e80-036f-11eb-96ba-1efddcffd1c6.png)

**Comment by timche** [comment]
This is looking good already!

I'd change the `Avg past 20 played` to `Play Rate` in %, so it's easier to read and understand. I'd also suggest some minor changes to the layout so it is similar to the player stats.

![image](https://user-images.githubusercontent.com/8075074/94966152-add6d100-04f4-11eb-8cb1-8a5927c83a8a.png)

What do you think?

**Comment by Morabotti** [comment]
Play Rate seems better. My only fear is that this takes too much vertical space. See image above; When we have two rows (percentages & descriptions), it takes more height than rosters. This would get even worse with 3 rows (adding Last 20 matches)

(already edited old photo before getting the new UI mockup)
![ddd](https://user-images.githubusercontent.com/42501026/94966755-75d88980-0506-11eb-85cd-8139b6bed9a7.png)

Originally I didn't want to add line between percentages & descriptions since rosters "last 20 matches" section doesn't have that either.  I can open new pull request with this updated UI.

**Comment by timche** [comment]
It can become quite awkward with the additional vertical space that it's taking, you are right.

![image](https://user-images.githubusercontent.com/8075074/94967525-2474ce00-04f7-11eb-9a29-7bb55440401a.png)

How about this?

**Comment by Morabotti** [comment]
![new](https://user-images.githubusercontent.com/42501026/94968938-7d9a2d00-050a-11eb-8ec7-7ad6ff06c50f.png)

With new UI, vetoing already overflows a bit. Currently there is 5px padding on both rows + 1px border.

**Comment by timche** [comment]
Holy. Yeah, this looks bad. 

How about putting the numbers below the map name?

```
Map
Avg. Play Rate / Win Rate: 21% / 46% vs. 82% / 53%
```

And add a hover with the question mark cursor with tooltip `Last 20 matches`. This might work?

**Comment by Morabotti** [comment]
How about this:

![new2](https://user-images.githubusercontent.com/42501026/94972344-bc7fb100-0511-11eb-8ef9-de6c42c4f29e.png)

We could also add `VS` block with border-left and right in the middle.

**Comment by poacher2k** [comment]
A bit late to the party, but I think this can be a very nice addition to the Enhancer suite. I'm a bit torn on Play Rate / PR though, as this needs explaining - as with the tooltip. Therefore, it might be worth considering simply stating the amount of matches played, as this might be self-explanatory: `1 Match / 100% WR` / `7 Matches / 63% WR`, etc.

Hopefully it is then intuitive that the former example is of much less significance ("It's only 1 game, might be luck") than the latter.

Also - and this needs testing - if we _really_ want to save real estate, the stats + map image + map name might all fit in 1 row. _Might_ ! 😅

**Comment by poacher2k** [comment]
@Morabotti : Any thoughts on my comment above? I really think we should avoid introducing acronyms if we can. I'd really like to get your PR merged in the near future :)

**Comment by poacher2k** [comment]
Closed by #98
