### ISSUE TITLE
Auto-Connect reconnects after changing tabs within FaceIT or after reopening the match room

### ISSUE THREAD

**Issue by PapeCoding** [faceit-enhancer/faceit-enhancer#101]
Once auto connect is enabled, you are not able to switch tabs in your match room anymore, since this will cause the game to reconnect to the server

This would be nice, if it could somehow store if it already issued a connect event and does not issue it again.

**Comment by callmeashish** [comment]
I this issue fixed, @PapeCoding? Please have a look and comment in the thread. Thanks.  :+1:

**Comment by PapeCoding** [comment]
I am still on version 2.10.20 and there the bug persists

**Comment by callmeashish** [comment]
Okay, I'll see if I can get it fixed @PapeCoding. Thanks 👍
