### ISSUE TITLE
Match room show player stats broken

### ISSUE THREAD

**Issue by poacher2k** [faceit-enhancer/faceit-enhancer#12]
Ref [this reddit thread](https://www.reddit.com/r/FACEITEnhancer/comments/8liy5w/match_room_show_player_stats_picking_phase_broken/)

![image](https://user-images.githubusercontent.com/2255960/40559181-2a6b5a4c-6056-11e8-84b3-dfd9aa59de92.png)

**Comment by timche** [comment]
It's hub match rooms only at captain player picks.

**Comment by timche** [comment]
@poacher2k or @ntmonson do you want and have time to try to fix it?

**Comment by poacher2k** [comment]
@timche : yup! this one has been a slow one as I've had to wait for hub queues to pop, which can take time. will try to look at it tonight / tomorrow.
