### ISSUE TITLE
Extensions is not finding an HTML element for elo panel

### ISSUE THREAD

**Issue by dnikoloski** [faceit-enhancer/faceit-enhancer#128]
- Browser: Firefox 109.0
- OS: Windows 11 latest build

This is what I get in the elo panel. [object HTMLDivElement][object HTMLSpanElement]

**Comment by shakerrrr** [comment]
Can confirm, same issue.

**Comment by jeffreyD0304** [comment]
Can confirm most, if not all 'enhanced' elements are no longer showing correctly.
![stats page example screenshot](https://user-images.githubusercontent.com/101135152/213883442-865c01bb-3c60-4f95-87f2-95190885fa55.png)

OS: Windows 10
Browser: Firefox 109.0

**Comment by timche** [comment]
This has already been fixed in [2.11.6](https://github.com/faceit-enhancer/faceit-enhancer/commit/66c12c6e3752804501f3775a4b2864a04e0909e9), but currently waiting for Mozilla for approval since Thursday. That is unfortunately out of my hands how long it will take.
