### ISSUE TITLE
After new update on mozilla HTMLDivElement][object HTMLSpanElement

### ISSUE THREAD

**Issue by Ant1Lamer** [faceit-enhancer/faceit-enhancer#129]
[object HTMLDivElement][object HTMLSpanElement] It shows this where supposed to be my lvl and elo and also when i go to my statistics where supposed to be my last 20 matches statistics, it shows this [object HTMLDivElement]

**Comment by roennow** [comment]
#127

**Comment by timche** [comment]
Already fixed: https://www.reddit.com/r/FACEITEnhancer/comments/10g81sg/firefox_were_aware_of_an_ongoing_issue_where/
