### ISSUE TITLE
Faceit sometimes shows incorrect count for people in queue

### ISSUE THREAD

**Issue by poacher2k** [faceit-enhancer/faceit-enhancer#13]
Ref image. It could make sense that we fetch the queue and update the number if we have newer data ?

![image](https://user-images.githubusercontent.com/2255960/40740460-38da7580-6449-11e8-9823-e8988238e52f.png)

**Comment by timche** [comment]
Good catch! Does it make sense that we fix it instead of FACEIT itself?

**Comment by poacher2k** [comment]
It definitively makes sense that this is something that faceit fixes itself, and I'm all for reporting bugs and unexpected behavior to the dev team (you especially) - I just have no insight into whether a minor thing like this would be a priority for them to fix.  If it's something they might fix next month, I don't see the point in fixing it here, but if it's in 6 months it might make sense to do it. 

Thoughts?
-- 
Mvh,
Daniel Skogly
Webutvikler
+47 977 93 446
pnkt.no

Den 30. mai 2018 22:48:42 CEST, skrev Tim Cheung <notifications@github.com>:

**Comment by timche** [comment]
Yeah, we don't have insights about their roadmap. I'm totally fine with fixing that if we have the ressources.
