### ISSUE TITLE
Elo Counter is Replaced by HTMLDivElement

### ISSUE THREAD

**Issue by PINPAL** [faceit-enhancer/faceit-enhancer#130]
**Description:**
The navbar Elo counter is replaced by HTMLDivElement text.
![image](https://user-images.githubusercontent.com/18197217/215046269-d12bf10e-d02f-4b2e-a44b-d4afbc4601f8.png)

**Versions:**
FaceItEnhancer 2.11.5
Firefox 109.0 (BuildID 20230112150232)

**Steps to Reproduce:**
1. Install FaceItEnhancer
2. Navigate to and sign into FaceIt
3. Observe elo counter displays text.

**Comment by timche** [comment]
Already fixed #127
