### ISSUE TITLE
js object rendered instead of value

### ISSUE THREAD

**Issue by tombrex** [faceit-enhancer/faceit-enhancer#131]
The faceit enhancer not showing the elo in the top bar but instead rendering the object, see screenshot elo.png.
Also, stats on the profile page are not shown from the enhancer, see screenshot stats.png.
Seems like they changed the objects and the enhancer cannot read it properly.
![elo](https://user-images.githubusercontent.com/46749354/215097777-ca7a2909-a4f4-4311-be4d-db19fec7f96e.PNG)
![stats](https://user-images.githubusercontent.com/46749354/215097791-50c7334e-78c1-42f1-a225-39838050c3ae.PNG)

**Comment by timche** [comment]
Already fixed
- #127 
- https://www.reddit.com/r/FACEITEnhancer/comments/10g81sg/firefox_were_aware_of_an_ongoing_issue_where/
