### ISSUE TITLE
Focus mode isn't hiding players inside of the lobby for me

### ISSUE THREAD

**Issue by gentrexha** [faceit-enhancer/faceit-enhancer#132]
I'm currently using Chrome and the latest version of Faceit Enhancer. I can't hide the player in the lobby using Focus mode.

**Comment by timche** [comment]
This got fixed with the newest version [2.11.8](https://github.com/faceit-enhancer/faceit-enhancer/commit/9c6861dcf628349fb27c352665926d9d7decb840).

**Comment by gentrexha** [comment]
That's great. Thanks!
