### ISSUE TITLE
UI Update - elo progression bar gone

### ISSUE THREAD

**Issue by Javeinne** [faceit-enhancer/faceit-enhancer#135]
The UI at the top has been changed a bit so the elo progression bar is no longer showing.

![image](https://user-images.githubusercontent.com/126281313/221255187-7c52157f-977a-4ae4-b7a6-3fe58261f5cb.png)

**Comment by timche** [comment]
This has already been fixed: https://github.com/faceit-enhancer/faceit-enhancer/commit/d2d1c9fd56c17c1a0b7462d9191adc8c345bdac6

**Comment by Javeinne** [comment]
I don't really know anything about these developing things. How do I fix it? I downloaded some zip file from the github page but I can't load it in my browser.

**Comment by timche** [comment]
You don't have to do anything. FACEIT Enhancer will be updated automatically for you. You just have to wait when it's available.

**Comment by Javeinne** [comment]
Okay thank you!

**Comment by itzshahay** [comment]
@timche Did something go wrong in the CI actions for Firefox? Because Mozilla hasn't received the `2.11.7` update yet

**Comment by timche** [comment]
> @timche Did something go wrong in the CI actions for Firefox? Because Mozilla hasn't received the `2.11.7` update yet


Nope, it's just Mozilla who takes a long times to review the new version. It can take several days until it has been approved and released on Firefox.

<img width="725" alt="Screenshot 2023-02-25 at 18 52 13" src="https://user-images.githubusercontent.com/8075074/221374589-3812671d-d5dd-469c-8ff6-a176ead0c949.png">
