### ISSUE TITLE
Lobby Stats Broken

### ISSUE THREAD

**Issue by CloudWolfYT** [faceit-enhancer/faceit-enhancer#136]
No longer displays stats of the lobby, must have been an update to faceit
![image](https://user-images.githubusercontent.com/64243799/221476208-c5427151-7897-4af0-831d-aa3127538f4d.png)

**Comment by Rishats** [comment]
@CloudWolfYT Hello, you closed this issue because you resolve this problem by your own?

**Comment by CloudWolfYT** [comment]
no i closed the issue because it may not be fixable

**Comment by timche** [comment]
This feature has been added natively on FACEIT, so you must enable it in your own game settings: https://www.faceit.com/en/settings/games
