### ISSUE TITLE
Don't work at all?

### ISSUE THREAD

**Issue by Rishats** [faceit-enhancer/faceit-enhancer#137]
Hello,after last update i can't see players stats at all(in match rooms). 

Tested via - Chrome,Opera,FireFox latest versions.

![Screenshot 2023-03-05 222855](https://user-images.githubusercontent.com/21194702/222973474-69594854-e8c2-4a2c-9d31-57c2f27b18a7.png)

Am I the only one with this problem?

**Comment by timche** [comment]
This feature has been added natively on FACEIT, so you must enable it in your own game settings: https://www.faceit.com/en/settings/games
