### ISSUE TITLE
Use elo diff for match room winPoints / lossPoints if available

### ISSUE THREAD

**Issue by poacher2k** [faceit-enhancer/faceit-enhancer#15]
If we have calculated the elo diff for a specific match with `mapMatchesByIdAndExtendElo`, we should use this for the match room winPoints / lossPoints, as the former is more likely to be correct (always?) in the time after the match has been played.

![image](https://user-images.githubusercontent.com/2255960/40741405-c68699ac-644b-11e8-96f0-2ee8bef7f645.png)

**Comment by timche** [comment]
Yes, that's right. But `mapMatchesByIdAndExtendElo` relies on the previous match to calculate the points. Our Elo calculation formula differs max. by -+1, don't know if that's a big issue. Nevertheless, nothing speaks against doing it right.

**Comment by poacher2k** [comment]
I'm wondering if this is more of an issue when some games have been played after the match was completed, as the players' elo will change over time. When a user revisits a match room, we don't have access to the historic team elos, and use the current team elos instead. This results in the winPoints and lossPoints showing what would be gained and won if the match was played _now_, instead of the time it was actually played. As shown in the image, the match room elo says +-30, but as you see in the sidebar it was +-15.

**Comment by timche** [comment]
Obsolete by #29
