### ISSUE TITLE
Support premade colors in match room v2

### ISSUE THREAD

**Issue by timche** [faceit-enhancer/faceit-enhancer#19]
Currently the premade colors are only working in match room v1: https://github.com/faceit-enhancer/faceit-enhancer/blob/master/src/content/features/add-match-room-player-colors.js#L22-L24

In some regions like Asia are now using match room v2 as in this bug report here: https://www.reddit.com/r/FACEITEnhancer/comments/942dx2/premade_colours_not_showing_for_awhile_now/

**Comment by timche** [comment]
@poacher2k do you maybe have time to look into this?

**Comment by poacher2k** [comment]
For sure! Will do when I'm back from vacation :)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by timche** [comment]
Thanks! No hurry, enjoy your vacation!
