### ISSUE TITLE
Incorrect ELO

### ISSUE THREAD

**Issue by okanozdemir** [faceit-enhancer/faceit-enhancer#23]
Faceit Enhancer shows my ELO incorrect for a long time, it is fixed 1100. My friends see it wrong in the same way.

![](https://i.imgur.com/6lokUPJ.png)
![](https://i.imgur.com/ElTpzLv.png)

My profile: https://www.faceit.com/en/players/Wrathxx
I'm using FACEIT Enchancer 1.6.9 on Chrome 70.0.3538.67.

**Comment by timche** [comment]
See https://www.reddit.com/r/FACEITEnhancer/comments/9k5qiu/remove_pubg_progress_bar/
