### ISSUE TITLE
Focus Mode

### ISSUE THREAD

**Issue by timche** [faceit-enhancer/faceit-enhancer#27]
https://www.reddit.com/r/FACEITEnhancer/comments/af0uqt/provide_an_official_method_to_censor_hide_all/

> could you provide some kind of option to hide all unimportant stuff? Some information is just annoying or making you feel bad right before a game. For myself I programmed a little script to hide ALL of it, but its not that "cool" for other people to use a script that is from a stranger like me. I just removed everything from the site, that got TagName "match-team-member-v2" or ClassName "text-muted". This made the lobbys censored, but I did not check it so far for lobbys that are not finished yet. Maybe this can help you out on this little request.
> 
> Would this be possible for you?
> 
> ( This is how the lobby looks for me now: 
> https://twitter.com/csgoruna/status/1083846260837224449 )

**Comment by sp0ok3r** [comment]
Can focus mode only hide match rooms where the user was played/playing?

**Comment by timche** [comment]
Yes, we will fix this.
