### ISSUE TITLE
Extention for new edge browser!

### ISSUE THREAD

**Issue by ias-t** [faceit-enhancer/faceit-enhancer#38]
new edge browser is build on chromium, so i think it's ease to put it on the marcket please!!

**Comment by dl-eric** [comment]
I am a fan of this idea, but since Chrome Web Store extensions can be directly added to Edge, I don't see why a developer would go through the overhead of putting it on Edge's store, except for professional reasons.

**Comment by timche** [comment]
> but since Chrome Web Store extensions can be directly added to Edge

I'm not familiar with how Edge extensions work, but if that's the case, nothing to do here. Thanks for the heads up @dl-eric!
