### ISSUE TITLE
Connect at 1 Minute left still fires after connect

### ISSUE THREAD

**Issue by joandrsn** [faceit-enhancer/faceit-enhancer#4]
Steps to reproduce:
Press "Connect at 1 Minute left".
Press "Go to server"
CS:GO opens and connects.
Match may start in that time.
"Connect at 1 Minute left"-triggers and now reconnects you to the server.

First time using the plugin I experience this and lost 1st round because of this.

Kinda stupid, yea. Maybe just set a flag when user has pressed "Go to server" button. If this flag is present, don't connect the user.

**Comment by timche** [comment]
Behaviour has been changed in version 1.3.0: https://www.reddit.com/r/FACEITEnhancer/comments/8f2jxc/version_130_sidebar_hubs_queue_various_fixes/
