### ISSUE TITLE
Disable solo queueing when in a party

### ISSUE THREAD

**Issue by mgeerse** [faceit-enhancer/faceit-enhancer#41]
Hey,

First of all thanks for the amazing extension, I use it everyday and have donated! ❤

I have a feature request:
When you are in a party (with other party members?) make the extension disable Solo Queue.
![Example](https://i.imgur.com/axIKEsy.png)

Thank you for your time.

**Comment by poacher2k** [comment]
Good suggestion! I can definitively see where this is coming from :)

**Comment by mgeerse** [comment]
> Good suggestion! I can definitively see where this is coming from :)

Yeah many times I have queue'd solo and accepted the match while thinking it was a "party queue" 😳

**Comment by maartenpaauw** [comment]
Hmm, good feature request! I'll like it. But maybe let it auto select "AS TEAM_X" rather than disabling it.

**Comment by timche** [comment]
> Hmm, good feature request! I like it. But maybe let it auto select "AS TEAM_X" rather than disabling it.

This has been implemented by FACEIT some time ago, so I guess we are good now :)
