### ISSUE TITLE
Off by one - Loss Points

### ISSUE THREAD

**Issue by dl-eric** [faceit-enhancer/faceit-enhancer#52]
Just played a game where FACEIT Enhancer reported we'd lose 0 ELO upon a loss. We ended up losing 1 ELO, so it seems that for every game, players must lose at least 1 ELO.

Consider changing src/content/helpers/elo.js line 14 from

`const lossPoints = round(K * (0 - percentage))`

to something like

`const lossPoints = max(1, round(K * (0 - percentage)))`

Although I'm not sure if the logic should be max(1, lossPoints) or that instead of round(), we should be doing ceil(). Guessing it's the former because I don't notice these off-by-one errors elsewhere.

(Match in question: https://www.faceit.com/en/csgo/room/1-65bf5bf4-efdd-4b43-a6f2-80da110574e0)

Happy to take this issue if the maintainer agrees with the change!

**Comment by timche** [comment]
There is actually a bug for both, win and loss. At the time of the implementation the minimum for a win was +10 and loss was possible to be +-0 if the difference was huge enough. FACEIT did some changes to the Elo system where the minimum for both is now +1 and -1.

I wouldn't mind if you want to contribute to this project.

**Comment by dl-eric** [comment]
Nice!
