### ISSUE TITLE
Lobby ELO lines are stacked on top of team name

### ISSUE THREAD

**Issue by dertzi** [faceit-enhancer/faceit-enhancer#56]
The lobby ELO text (AVG. ELO: xx / DIFF: xx && EST. WIN: xx / EST. LOSS: xx) is stacked on top of the team names.

It seems that the h2 element containing the team name has the style: "line-height: 0px;". Removing this style from the H2 element fixes the issue.

Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
OS: Windows 10
FACEIT Enhancer: 2.9.3
 
![image](https://user-images.githubusercontent.com/5425187/79080944-ad1d6900-7d21-11ea-8d76-9a90c96f6969.png)

**Comment by poacher2k** [comment]
This was already fixed in #54 and released yesterday.
