### ISSUE TITLE
New FACEIT style update breaks matchroom stuff

### ISSUE THREAD

**Issue by dl-eric** [faceit-enhancer/faceit-enhancer#58]
See the image:
![bug](https://i.imgur.com/A7dhyyY.png)

**Comment by phoecz** [comment]
ye fix pls

**Comment by dl-eric** [comment]
Probably just need more margin-top. Will check it out the next time I queue

**Comment by timche** [comment]
Has been already fixed and released: fdd3fd8c36ce04b42196ea9b54fd681049f1785f

But we are waiting for Chrome Web Store review which takes a long time.
