### ISSUE TITLE
Add "Contributor" badges to contributors?

### ISSUE THREAD

**Issue by dl-eric** [faceit-enhancer/faceit-enhancer#59]
Thoughts on a badge awarded to contributors to this open source project? Would be pretty neat I think :)

**Comment by timche** [comment]
Sure, but most players don't know what "Contributor" means, so we'd need to have a simplified title. Thanks for your contributions so far.

**Comment by timche** [comment]
@dl-eric @maartenpaauw @josiahpwhite @Morabotti can you please give me links to your FACEIT profile? I'd like to add the contributor badge if you want.

**Comment by Morabotti** [comment]
@timche, Thanks:
https://www.faceit.com/en/players/Morabotti
guid: 4fc92ac4-100b-4cf0-b8f6-5420cdb48ce3

**Comment by dl-eric** [comment]
@timche Thanks!
https://www.faceit.com/en/players/xPie-
guid: 97a310e5-1668-46b1-b6f1-93df1463ff4a

What were you thinking besides the title "Contributor"?

**Comment by timche** [comment]
I guess I just stick with "Contributor" as it's the most "correct" word and I can't think of another word tbh.

**Comment by maartenpaauw** [comment]
@timche thank you! 

https://www.faceit.com/en/players/m44rt3np44uw

**Comment by josiahpwhite** [comment]
@timche Really appreciate it!

https://www.faceit.com/en/players/Mello_Jello
