### ISSUE TITLE
Restore official map names

### ISSUE THREAD

**Issue by claudiobernasconi** [faceit-enhancer/faceit-enhancer#64]
I get offended by FaceIt changing the official map names in the match lobby from e.g. de_overpass to Overpass. I'd like to add an option to the FaceIt enhancer that allows the user to enable official map names again.

What do you think of this?

If you think this would be valuable, I'll develop some code and provide a PR for this request.

**Comment by timche** [comment]
Thanks for opening this issue @claudiobernasconi.

I understand your point, but I don't see this as a potential feature in FACEIT Enhancer. Give the new map names some more time and I guess you will get used to it.

If you think this is an issue, I'd advise you to also give feedback to FACEIT directly.
