### ISSUE TITLE
Ability to add custom notes to players

### ISSUE THREAD

**Issue by Morabotti** [faceit-enhancer/faceit-enhancer#67]
Adding an ability to add custom notes to players either in lobbies or profiles. A new icon button could be added to the `Last 20 Matches` section in lobby or in `match-team-member__controls` section. Notes could be stored in browsers local storage in a key/value type object.

There might be some challenges regarding inputting. Maybe custom dialog containing text field? This should be investigated.

What do you think about this feature. Worth creating?

**Comment by timche** [comment]
> There might be some challenges regarding inputting. Maybe custom dialog containing text field? This should be investigated.

Using [`window.promp()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) should be sufficient.

Regardless of this, what are actual use cases for this? I can't think of any useful right now.

**Comment by Morabotti** [comment]
window.prompt would be simple and effective.

I think the primary use case for this feature is to leave notes about players, good or bad. Lets say you are playing with exceptionally good player and want to remember it in future. Usually I remember familiar names but can't recall when/how he played or which kind of player he is.

I see some risk in this too. Some players might use this feature to create "int lists"/"troll lists", therefore this might lead to toxic behavior in upcoming matches. After all, if there are player who uses these kinds of lists, this feature will help them with that. But for rest of us, it creates way to remember players skills, attributes, likeness, play style etc...

**Comment by Morabotti** [comment]
Closing this issue after long consideration. This feature seemed fine at the time of writing but now this feels pretty useless "tool" for tryhard/toxic people.

If this kind of tool is implemented, it should be done internally by faceit.
