### ISSUE TITLE
Incorrect win rate calculation for last 20 matches?

### ISSUE THREAD

**Issue by danieladugyan** [faceit-enhancer/faceit-enhancer#71]
This is quite a minor issue, but the win rate for the last 20 matches seems to be calculated incorrectly. I'm assuming _win rate_ is supposed to refer to the ratio between _matches won_ and _matches played_. However, this means that all win rates must be evenly divisible by **1/20**. Currently, this is not the case as Faceit Enhancer reports winrates such as **67%** and **44%**. It can't be a rounding error either, as the nearest possible win rate for **67%** is either **65%** or **70%**.

(A win rate of **67%** would mean winning **13.4** matches out of **20**. If **67%** is **2/3** rounded up, it'd still not work as that would mean winning **13.3** matches out of **20**.)

![image](https://user-images.githubusercontent.com/26229521/88285845-15e88a00-ccf0-11ea-86fd-b321a95a055a.png)

**Comment by timche** [comment]
I think this can happen when a player has played a non matchmaking 5v5 match in his last 20 matches. So in reality when someone has played 20 matches, 19 of them are 5v5, 1 of them is 1v1, then the win rate of 19 matches is actually calculated.

You can check calculation here: https://github.com/faceit-enhancer/faceit-enhancer/blob/master/src/content/helpers/stats.js#L44-L48

**Comment by danieladugyan** [comment]
Oh, I see. I went back and checked the match history for every player with a "weird" win rate, and that does indeed seem to be the case. Thank you for clarifying!
