### ISSUE TITLE
Implement validation to users social media links

### ISSUE THREAD

**Issue by Morabotti** [faceit-enhancer/faceit-enhancer#73]
Lately I have encountered multiple users who have troll facebook/youtube/twitter urls that are actually screamers. Enhancer could validate profile urls and disable them if they don't match with certain regex queries. Invalid links in lobbies would be filtered out entirely.

**Comment by timche** [comment]
Sounds good. Would you mind opening a PR?

**Comment by Morabotti** [comment]
Merged.

**Comment by timche** [comment]
Btw, you can link and auto-close this issue when you mention this issue in your commit or PR: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
