### ISSUE TITLE
Show teams if match has been cancelled

### ISSUE THREAD

**Issue by Morabotti** [faceit-enhancer/faceit-enhancer#75]
While ago enhancer had match preview feature where you could see your enemies and your teammates before match has 
been started. After that got abused, Faceit fixed match API so enhancer couldn't utilize this feature. But after investigating how match API works, I found out that when match state is CANCELLED, endpoint shows all the teams, players, etc..

This opens up many things. We could re-implement this old feature and show it in the "Someone didn't accept" dialog. Most of old logic & UI still probably works and could be reused.

In addition of old UI, we could add maps that would've been available in the lobby.

What do you think? Would faceit block this API too if implemented?

**Comment by timche** [comment]
> While ago enhancer had match preview feature where you could see your enemies and your teammates before match has
been started.
This has never been a feature actually, because it just leads to negative actions such as dodging. Are you mistaking it with another extension?

> We could re-implement this old feature and show it in the "Someone didn't accept" dialog.
> [...]
> In addition of old UI, we could add maps that would've been available in the lobby.
What actual value does it bring to the user? The match is cancelled already and not played.

**Comment by Morabotti** [comment]
> This has never been a feature actually, because it just leads to negative actions such as dodging. Are you mistaking it with another extension?

Yeah, that is actually true. There was one other extension back in the day. My bad.

> We could re-implement this old feature and show it in the "Someone didn't accept" dialog.
[...]
In addition of old UI, we could add maps that would've been available in the lobby.

Most of the times lobbies stay the same after someone dodges. This feature could scout potential next games (map pools/elo estimates/enemy players/premades/teammates). Of course this will sometimes result in pregame dodges, but it comes not even close to been as bad as it was before.

If you don't believe this is right feature for this extension, feel free to close this issue. Just throwing up ideas here :)

**Comment by timche** [comment]
> This feature could scout potential next games (map pools/elo estimates/enemy players/premades/teammates).

After someone dodges, they are banned from the queue for a minute or so. The chance both lobbies will meet other again is rather low I'd say and within the minute you'd find new opponents already. After all, this could lead to the same destructive behaviour of dodging which I don't like to promote, sorry.

**Comment by Morabotti** [comment]
Okay, no problem.

> After someone dodges, they are banned from the queue for a minute or so. The chance both lobbies will meet other again is rather low I'd say and within the minute you'd find new opponents already. 

This was never meant for the one who dodged the match, more to the people who still were in queue.
